version: "3.8"

services:
  api:
    container_name: bike_api
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_bike
    image: postgres:16.4
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: always